language: ruby
rvm:
  - 2.1
  - 2.2

services:
  - postgresql

addons:
  postgresql: "9.4"

before_install:
  - gem update bundler
  # - pg_ctl -D /usr/local/var/postgres start # https://github.com/travis-ci/travis-ci/issues/1875

before_script:
  - sudo rm /etc/apt/sources.list.d/ubuntugis-stable-source.list # https://github.com/travis-ci/travis-ci/issues/2401
  - sudo apt-get update -qq
  - sudo apt-get install gdal-bin -y
  # - sudo apt-get install postgresql-9.4-postgis-2.1 -y # these are removed by installing gdal-bin
  - psql -c "create extension postgis" -U travis -d travis
  # - brew update
  # https://serverfault.com/questions/662176/postgres-on-os-x-cant-find-postgis-extension-control-file
  # - brew uninstall gdal
  # - brew install gdal --with-postgresql # https://gis.stackexchange.com/questions/33346/how-can-i-update-ogr2ogr-to-include-the-postgresql-driver

script: bundle exec rspec spec
