language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -c 'create extension postgis;'

before_install:
  - sudo apt-get -qq update
  # http://askubuntu.com/questions/206593/how-to-install-rgdal-on-ubuntu-12-10
  - sudo apt-get install -y aptitude
  - sudo aptitude install -y libgdal-dev libproj-dev

script: bundle exec rspec spec
