language: ruby
rvm:
  - 2.1

before_install:
  - gem update bundler

before_script:
  - psql -c 'create extension postgis;' -U travis -d postgres # use default user & db

script: bundle exec rspec spec
