os:
  - osx

language: ruby
rvm:
  - 2.1

services:
  - postgresql

addons:
  postgresql: "9.4"

before_install:
  - gem update bundler
  - brew update

before_script:
  - ps auxw | grep postgres # is postgres running?!
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -c 'create extension postgis;'

script: bundle exec rspec spec
