os:
  - osx

language: ruby
rvm:
  - 2.1

before_install:
  - gem update bundler
  - pg_ctl -D /usr/local/var/postgres start # https://github.com/travis-ci/travis-ci/issues/1875

before_script:
  - brew update
  - brew uninstall gdal # dyld: Library not loaded: /usr/local/lib/libspatialite.5.dylib error
  - brew install gdal --with-postgresql # https://gis.stackexchange.com/questions/33346/how-can-i-update-ogr2ogr-to-include-the-postgresql-driver

script: bundle exec rspec spec
