language: ruby

addons:
  postgresql: "9.3"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -c "create extension postgis" -d travis_ci_test

before_install:
  - gem update bundler
  # http://askubuntu.com/questions/206593/how-to-install-rgdal-on-ubuntu-12-10
  - sudo apt-get update -qq
  - sudo apt-get install -y aptitude
  - sudo aptitude install -y libgdal-dev libproj-dev

rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.3
  - rbx-2.9

script: bundle exec rspec spec
