os:
  - osx

language: ruby
rvm:
  - 2.1

before_install:
  - gem update bundler
  - brew update
  - brew install tree
  - pg_ctl -D /usr/local/var/postgres start # https://github.com/travis-ci/travis-ci/issues/1875

before_script:
  - brew info postgres
  - brew info postgis
  - tree /usr/local/Cellar/postgresql/9.3.5_1
  - psql -c 'create extension postgis;' -U travis -d postgres # use default user & db

script: bundle exec rspec spec
