language: ruby
rvm:
  - 2.1
  - 2.2

services:
  - postgresql

addons:
  postgresql: "9.4"

before_install:
  - gem update bundler

before_script:
  - sudo rm /etc/apt/sources.list.d/ubuntugis-stable-source.list # https://github.com/travis-ci/travis-ci/issues/2401
  - sudo apt-get update -qq
  - sudo apt-get install gdal-bin -y
  - psql -c "create extension postgis" -U $USER -d $USER # default db name is same as user
  - echo $HOME

script: bundle exec rspec spec
