os:
  - osx

language: ruby
rvm:
  - 2.1

before_install:
  - gem update bundler
  - brew update
  - pg_ctl -D /usr/local/var/postgres start # https://github.com/travis-ci/travis-ci/issues/1875

before_script:
  - psql createuser -d postgres
  - psql create database travis_ci_test -U postgres
  - psql create extension postgis -U postgres

script: bundle exec rspec spec
