os:
  - osx

language: ruby
rvm:
  - 2.1

addons:
  postgresql: "9.4"

before_install:
  - gem update bundler
  - brew update
  - pg_ctl -D /usr/local/var/postgres start # https://github.com/travis-ci/travis-ci/issues/1875

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -c 'create extension postgis;'

script: bundle exec rspec spec
