os:
  - osx

language: ruby
rvm:
  - 2.1

before_install:
  - gem update bundler

before_script:
  - brew update
  # https://serverfault.com/questions/662176/postgres-on-os-x-cant-find-postgis-extension-control-file
  - brew info postgres
  - brew uninstall postgres
  - brew uninstall postgis
  - brew install postgresql-9.3
  - brew install postgis
  - pg_ctl -D /usr/local/var/postgres start # https://github.com/travis-ci/travis-ci/issues/1875
  - psql -c 'create extension postgis;' -U travis -d postgis

script: bundle exec rspec spec
