os:
  - osx

language: ruby
rvm:
  - 2.1
  - 2.2

services:
  - postgresql

addons:
  postgresql: "9.4"

before_install:
  - gem update bundler
  - brew update
  - brew install gdal

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -c 'create extension postgis;'

script: bundle exec rspec spec
