os:
  - osx

language: ruby
rvm:
  - 2.1

before_install:
  - gem update bundler

before_script:
  - brew update
  # https://serverfault.com/questions/662176/postgres-on-os-x-cant-find-postgis-extension-control-file
  - brew info postgres
  - brew uninstall postgres
  - brew uninstall postgis
  - brew install postgres
  - brew install postgis
  # - brew uninstall gdal
  # - brew install gdal --with-postgresql # https://gis.stackexchange.com/questions/33346/how-can-i-update-ogr2ogr-to-include-the-postgresql-driver
  - pg_ctl -D /usr/local/var/postgres start # https://github.com/travis-ci/travis-ci/issues/1875
  - psql -c 'create extension postgis;' -U travis -d postgis

script: bundle exec rspec spec
